In [2]:
import numpy as np

## 1. Data Types & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]],
               [[19, 20, 21],
                [22, 23, 24],
                [25, 26, 27]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [16]:
a3.shape

(3, 3, 3)

In [18]:
# Number of dimensions on the array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [19]:
# Data Type of each array
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [20]:
# Array size (number of elements)
a1.size, a2.size, a3.size

(3, 6, 27)

In [21]:
# Type of each array
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# Create a DataFrane from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [24]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
type(ones)

numpy.ndarray

In [31]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [44]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 2, 9, 5, 5],
       [3, 3, 5, 1, 4],
       [8, 4, 4, 2, 9]])

In [45]:
random_array.size

15

In [46]:
random_array.shape

(3, 5)

In [49]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.41546419, 0.48457985, 0.70532266],
       [0.25821911, 0.20142897, 0.85283343],
       [0.37134113, 0.5266472 , 0.07591918],
       [0.84603208, 0.76745685, 0.45571419],
       [0.67540039, 0.87085144, 0.14420431]])

In [50]:
random_array_2.shape

(5, 3)

In [51]:
random_array_3 = np.random.rand(5, 3)
random_array_2

array([[0.41546419, 0.48457985, 0.70532266],
       [0.25821911, 0.20142897, 0.85283343],
       [0.37134113, 0.5266472 , 0.07591918],
       [0.84603208, 0.76745685, 0.45571419],
       [0.67540039, 0.87085144, 0.14420431]])

In [52]:
# Pseudo-random numbers
np.random.seed()